#!/bin/bash
# Write the AUR-shaped PKGBUILD from the working-tree one.
#
# There are two PKGBUILDs because they answer to different rules and cannot be
# one file. packaging/PKGBUILD builds from a local checkout, which is what
# makes `makepkg -si` work on a change that has not been published yet. The
# AUR will not accept that: a package there has to fetch a versioned source
# from a URL and check it against a sha256sum, so it can only ever build a
# release that already exists.
#
# Keeping both by hand would let their dependency lists drift, and a wrong
# dependency is exactly the class of bug this project has already shipped
# once. So the metadata is read out of packaging/PKGBUILD and only the source
# and its checksum are added here. Edit that file, run this, commit both.
#
# Usage:
#   update-aur-pkgbuild.sh [version]   write it, fetching the tarball to hash
#   update-aur-pkgbuild.sh --check     confirm the committed file is current
#
# --check regenerates using the version and checksum already recorded in the
# file, so it needs no network and answers only one question: has the metadata
# drifted from packaging/PKGBUILD?
#
# It deliberately does not judge the version or the checksum. The two files are
# expected to disagree about pkgver — this one tracks the last release, the
# working-tree PKGBUILD tracks whatever is being built now — and a checksum
# cannot be verified without fetching the tarball. Both are checked for real
# by the install-arch-from-aur job, where makepkg downloads the source named
# here and refuses it if the sum does not match, and a version that was never
# tagged simply fails to download.
set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_PKGBUILD="$PROJECT_DIR/packaging/PKGBUILD"
TARGET="$PROJECT_DIR/packaging/aur/PKGBUILD"

CHECK=false
VERSION=""
for argument in "$@"; do
  case "$argument" in
    --check) CHECK=true ;;
    -h|--help) sed -n '2,25p' "$0"; exit 0 ;;
    -*) echo "Unknown option: $argument" >&2; exit 2 ;;
    *) VERSION="$argument" ;;
  esac
done

# The working-tree PKGBUILD is the single source of the metadata. Sourcing it
# is safe: package() is only defined here, never called, and source=() is
# empty so nothing is fetched.
# shellcheck source=/dev/null
source "$SOURCE_PKGBUILD"

# Every pkgname, pkgdesc, depends and the rest came from the file sourced
# above, which shellcheck cannot see into. That is the whole point: they are
# not assigned here so that there is only one place to edit them.
# shellcheck disable=SC2154
emit() {
  local version="$1" checksum="$2"
  cat <<HEADER
# Maintainer: Mohamed El-Etreby <40498+etreby@users.noreply.github.com>
#
# Generated by scripts/update-aur-pkgbuild.sh. Do not edit by hand: the
# dependency lists come from packaging/PKGBUILD, so edit that one and run the
# script, or the two will disagree about what this package needs.
#
# This is the AUR-acceptable form. It fetches a released tarball and checks it
# against a sha256sum, which is what the AUR requires and which also means it
# can only build a version that has been released. packaging/PKGBUILD is the
# one to use on a local checkout of unreleased work.
pkgname=$pkgname
pkgver=$version
pkgrel=$pkgrel
pkgdesc="$pkgdesc"
arch=($(printf "'%s' " "${arch[@]}" | sed 's/ $//'))
url="$url"
license=($(printf "'%s' " "${license[@]}" | sed 's/ $//'))
depends=($(printf "'%s' " "${depends[@]}" | sed 's/ $//'))
optdepends=(
HEADER
  printf "  '%s'\n" "${optdepends[@]}"
  cat <<FOOTER
)
source=("\$pkgname-\$pkgver.tar.gz::$url/archive/refs/tags/v\$pkgver.tar.gz")
sha256sums=('$checksum')

package() {
  local project="\$srcdir/\$pkgname-\$pkgver"
  "\$project/scripts/stage-package.sh" "\$pkgdir" /usr
  install -Dm644 "\$project/LICENSE" "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
}
FOOTER
}

if $CHECK; then
  test -f "$TARGET" || { echo "$TARGET does not exist; run this without --check" >&2; exit 1; }
  recorded_version=$(sed -n 's/^pkgver=//p' "$TARGET" | head -1)
  recorded_checksum=$(sed -n "s/^sha256sums=('\\(.*\\)')/\\1/p" "$TARGET" | head -1)
  if [ -z "$recorded_version" ] || [ -z "$recorded_checksum" ]; then
    echo "$TARGET has no pkgver or sha256sums to check against" >&2
    exit 1
  fi
  if diff -u "$TARGET" <(emit "$recorded_version" "$recorded_checksum"); then
    echo "The AUR PKGBUILD matches packaging/PKGBUILD."
    exit 0
  fi
  echo >&2
  echo "The AUR PKGBUILD has drifted from packaging/PKGBUILD." >&2
  echo "Run scripts/update-aur-pkgbuild.sh and commit the result." >&2
  exit 1
fi

if [ -z "$VERSION" ]; then
  VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' "$PROJECT_DIR/pyproject.toml" | head -1)"
fi
TARBALL="$url/archive/refs/tags/v$VERSION.tar.gz"
echo "Fetching $TARBALL to hash it…" >&2
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT
if ! curl -fsSL -o "$SCRATCH/source.tar.gz" "$TARBALL"; then
  echo "Could not fetch $TARBALL." >&2
  echo "An AUR package can only build a released version, so tag and push v$VERSION first." >&2
  exit 1
fi
CHECKSUM="$(sha256sum "$SCRATCH/source.tar.gz" | cut -d' ' -f1)"

mkdir -p "$(dirname "$TARGET")"
emit "$VERSION" "$CHECKSUM" > "$TARGET"
echo "Wrote $TARGET for v$VERSION ($CHECKSUM)"
